// Keep both supported locales together for the bounded operations overview feature.
const messages = {
  backupTitle: ['配置备份摘要', 'Configuration backup summary'], backupDevice: ['备份设备', 'Backup device'], readBackup: ['读取最近备份', 'Read latest backup'], noBackup: ['尚无已保存的备份记录', 'No saved backup records'], savedBackup: ['最近已保存备份', 'Latest saved backup'], backupRedacted: ['已脱敏', 'Redacted'], backupUnredacted: ['未脱敏', 'Not redacted'], backupRedactionFailed: ['脱敏失败', 'Redaction failed'], backupScope: ['按需读取选中设备；此接口不包含采集失败的尝试记录', 'Read the selected device on demand; failed capture attempts are not included in this API'],
  collectedSize: ['已采集', 'Collected'],
  searchHint: ['名称、地址或资源 ID', 'Name, address or resource ID'], instanceRatio: ['按实例数量统计', 'Share of instance count'], scopeTotal: ['当前筛选合计', 'Total in current filter'], sampleCoverage: ['最近采样覆盖', 'Latest sample coverage'], partialCapacity: ['仅含已采集实例，不代表完整总量', 'Collected instances only; not a complete total'], dataNotes: ['数据说明', 'About this data'],
  expandGaps: ['展开采集缺口', 'Expand collection gaps'], networkManageHint: ['接入设备并配置采集后，可查看可达性、CPU、内存与配置备份记录。', 'Connect a device and configure collection to view reachability, CPU, memory and saved configuration backups.'],
  title: ['运维总览', 'Operations overview'], all: ['综合态势', 'Situation'], instance: ['数据库', 'Databases'], server: ['服务器', 'Servers'], network_device: ['网络设备', 'Network devices'],
  refresh: ['刷新', 'Refresh'], refreshing: ['刷新中', 'Refreshing'], dataTime: ['快照更新', 'Snapshot updated'], observed: ['最近观测', 'Last observed'], unknown: ['未知', 'Unknown'],
  resources: ['纳管资源', 'Managed resources'], instances: ['数据库实例', 'Database instances'], abnormalResources: ['异常资源', 'Abnormal resources'], abnormalInstances: ['异常实例', 'Abnormal instances'], unavailableServers: ['不可用服务器', 'Unavailable servers'], unreachableDevices: ['不可达设备', 'Unreachable devices'], alerts: ['未解决告警', 'Unresolved alerts'], collectionRisk: ['采集异常资源', 'Collection gaps'], coverage: ['采集覆盖率', 'Collection coverage'], freshCoverage: ['最近观测有效', 'Recent observations valid'],
  dedup: ['按资源去重', 'Distinct resources'], acknowledged: ['包含已确认但未解决', 'Includes acknowledged, unresolved alerts'], atLeast: ['至少', 'At least'], incomplete: ['数据不完整：仅展示有界范围，下界不能代表全量统计', 'Incomplete bounded snapshot: lower bounds are not full totals'],
  scopeSearch: ['搜索资源', 'Search resources'], engine: ['数据库引擎', 'Database engine'], allEngines: ['全部引擎', 'All engines'], clear: ['清除筛选', 'Clear filters'],
  riskQueue: ['风险队列', 'Risk queue'], allRisks: ['查看全部', 'View all'], topFive: ['优先展示前 5 项', 'Showing the first 5 priorities'],
  normal: ['正常', 'Normal'], abnormal: ['异常', 'Abnormal'], unavailable: ['不可用', 'Unavailable'], unreachable: ['不可达', 'Unreachable'], fresh: ['有效', 'Valid'], stale: ['已过期', 'Expired'], missing: ['无数据', 'No data'], failed: ['采集失败', 'Collection failed'], qualityGap: ['指标部分可用或质量异常', 'Partial metrics or quality gaps'], previous: ['上次状态', 'Last known state'],
  viewResource: ['查看资源', 'View resource'], evidence: ['查看证据', 'View evidence'], diagnose: ['只读诊断', 'Read-only diagnosis'], noAi: ['无只读诊断权限，需要 ai:manage', 'Read-only diagnosis requires ai:manage'],
  health: ['运行状态分布', 'Operating state distribution'], collection: ['采集质量', 'Collection quality'], relations: ['关联资源', 'Related resources'], relationHint: ['关联关系仅代表潜在影响，不代表故障因果', 'Relationships indicate potential impact, not causation'], selectRisk: ['选择风险查看关联摘要', 'Select a risk to view relationships'], noRelations: ['未建立关系', 'No relationships established'], relationUnavailable: ['关联信息不可用', 'Relationship information unavailable'], relationUnknown: ['关联证据尚未获取', 'Related evidence has not been fetched'],
  details: ['资源明细与证据', 'Resources and evidence'], name: ['资源名称', 'Resource name'], address: ['地址', 'Address'], model: ['型号', 'Model'], runtime: ['运行状态', 'Operating state'], collected: ['采集状态', 'Collection state'], actions: ['操作', 'Actions'], selectedFilter: ['明细筛选', 'Detail filter'], page: ['页', 'Page'], prev: ['上一页', 'Previous'], next: ['下一页', 'Next'],
  noManaged: ['尚未纳管', 'No managed'], noMatch: ['当前筛选无结果', 'No resources match the current filters'], noRisks: ['当前观测未发现异常', 'Current observations show no abnormalities'], unknownHealth: ['尚无足够观测判断运行状态', 'Insufficient observations to determine health'], manage: ['纳管资源', 'Manage resources'], manageHint: ['配置纳管与采集后可查看观测；未知不代表正常', 'Configure resource collection to view observations; unknown does not mean healthy'], permission: ['当前账号无此类资源查看权限', 'You do not have permission to view this resource type'], unavailableData: ['数据不可用', 'Data unavailable'], retry: ['重试', 'Retry'], retained: ['保留上次成功快照', 'Retaining the last successful snapshot'],
  metrics: ['专业指标 · Top 5', 'Metrics · Top 5'], metric: ['指标', 'Metric'], cpu_usage: ['CPU 使用率', 'CPU usage'], memory_usage: ['内存使用率', 'Memory usage'], disk_usage: ['磁盘使用率', 'Disk usage'], connections: ['连接数', 'Connections'], qps: ['QPS', 'QPS'], device_cpu_percent: ['设备 CPU', 'Device CPU'], device_memory_percent: ['设备内存', 'Device memory'], device_temperature_celsius: ['温度', 'Temperature'],
  effective: ['有效资源', 'Resources with valid values'], unsupported: ['不支持', 'Unsupported'], invalid: ['无效', 'Invalid'], noMetric: ['缺少有效观测；不补零，不推断正常', 'No valid observations; missing values are not zero or healthy'], latestOnly: ['仅最新有效观测；历史趋势请进入资源详情', 'Latest valid observations only; open resource details for history'], comparable: ['按引擎分组比较，未配置阈值时不判定过载', 'Compare within each engine; no overload inference without configured thresholds'], mean: ['资源均值', 'Resource mean'], sum: ['合计', 'Sum'],
  dbTypes: ['数据库类型占比', 'Database type distribution'], capacity: ['总数据量趋势', 'Total data size trend'], localFilter: ['局部筛选，仅作用于容量图', 'Local filter: capacity chart only'], chooseInstance: ['统计范围', 'Capacity scope'], custom: ['自定义', 'Custom'], start: ['开始日期', 'Start date'], end: ['结束日期', 'End date'], apply: ['应用日期', 'Apply dates'], invalidDates: ['请选择有效起止日期，结束日期不得早于开始日期或晚于今天', 'Choose valid dates; end must not precede start or be in the future'], noCapacity: ['当前范围暂无容量观测', 'No capacity observations in this range'], capacityGaps: ['采样缺口断线；未提供总容量，不推算剩余或耗尽时间', 'Sampling gaps are disconnected; no remaining capacity or exhaustion estimates'],
  timeInvalid: ['时间异常', 'Invalid time'], alertUnavailable: ['告警读取不可用，数量为已知下界', 'Alerts unavailable; count is a known lower bound'], failure: ['模块加载失败', 'Module failed to load'], backup: ['配置备份记录可在设备详情查看', 'View configuration backup records in device details'],
} as const;
export const operationsOverviewZh = Object.fromEntries(Object.entries(messages).map(([key, value]) => [key, value[0]]));
export const operationsOverviewEn = Object.fromEntries(Object.entries(messages).map(([key, value]) => [key, value[1]]));
