/**
 * ScriptEditor — CodeMirror 6 SQL editor wrapper as LitElement
 *
 * Provides syntax-highlighted SQL editing with dialect switching per dbType.
 * Content changes are emitted as CustomEvent('content-change') for parent
 * components to consume.
 */
import { LitElement, html, css } from "lit";
import { customElement, property } from "lit/decorators.js";
import { basicSetup } from "codemirror";
import { EditorView } from "@codemirror/view";
import { EditorState } from "@codemirror/state";
import { sql, MySQL, PostgreSQL, SQLDialect } from "@codemirror/lang-sql";
import { oneDark } from "@codemirror/theme-one-dark";

/* ───── Dameng DM8 dialect ───── */
const DamengDialect = SQLDialect.define({
  keywords: `
    ABORT ABS ABSOLUTE ACCESS ACTION ACTIVE ADD ADMIN AFTER AGGREGATE
    ALL ALLOCATE ALTER ANALYZE AND ANY ARCHIVELOG ARE ARRAY AS ASC
    ASSERTION AT AUTHORIZATION AUTO BACKUP BACKWARD BATCH BEFORE BEGIN
    BETWEEN BIGINT BINARY BIT BLOB BLOCK BODY BOOLEAN BOTH BREADTH
    BREAK BROWSE BULK BY CACHE CALL CALLED CASCADE CASCADED CASE CAST
    CATALOG CHANGE CHAR CHARACTER CHECK CHECKPOINT CLASS CLOB CLOSE
    CLUSTER CLUSTERED COALESCE COLLATE COLUMN COLUMNS COMMENT COMMIT
    COMMITTED COMPUTE CONNECT CONNECTION CONSTRAINT CONSTRAINTS
    CONTAINS CONTAINSTABLE CONTINUE CONVERT CORRESPONDING COUNT CREATE
    CROSS CUBE CURRENT CURRENT_DATE CURRENT_TIME CURRENT_TIMESTAMP
    CURRENT_USER CURSOR CYCLE DATA DATABASE DATABASES DATE DAY DBCC
    DEALLOCATE DEC DECIMAL DECLARE DEFAULT DEFERRABLE DEFERRED
    DELETE DENY DEPTH DESC DESCRIBE DESCRIPTOR DETERMINISTIC DIAGNOSTICS
    DIRECTORY DISABLE DISCONNECT DISK DISTINCT DISTRIBUTED DM DOMAIN
    DOUBLE DROP DUMMY DUMP DYNAMIC EACH ELSE ENABLE ENCLOSED END
    ERRLVL ERROR ERRORS ESCAPE ESTIMATE EVENT EXCEPT EXCEPTION EXEC
    EXECUTE EXISTS EXIT EXPLAIN EXTERNAL EXTRACT FALSE FETCH FILE
    FILLFACTOR FIRST FLOAT FLUSH FOLLOWING FOR FOREIGN FORTRAN FOUND
    FREE FREEPAGECLS FREETEXT FREETEXTTABLE FROM FULL FUNCTION
    GENERAL GENERATED GET GLOBAL GO GOTO GRANT GROUP GROUPING HAVING
    HOLD HOUR IDENTITY IF IMMEDIATE IN INDEX INDEXES INDICATOR INFILE
    INHERIT INITIAL INITIALLY INNER INOUT INPUT INSENSITIVE INSERT
    INSTEAD INT INTEGER INTERSECT INTERVAL INTO IS ISOLATION ITERATE
    JOIN KEY KILL LANGUAGE LARGE LAST LATERAL LDR LEAKPROOF LEFT
    LEVEL LIKE LIMIT LINEAR LINENO LOAD LOCAL LOCALTRANS LOCATION
    LOCK LOGFILE LOGIN LOOP LOW_PRIORITY MAIN MANUAL MATCH MAXVALUE
    MESSAGE_BYTE_MULTIPLIER MERGE MINVALUE MINUS MODE MODIFIES
    MODIFY MODULE MONTH MOVE MULTISET NATURAL NCHAR NEW NEXT NO NODE
    NOCHECK NONCLUSTERED NONE NOT NULL NULLIF NUMBER NUMERIC OF OFFLINE
    OFFSET OFFSETROWS OLD ON ONLINE ONLY OPEN OPENDATASOURCE
    OPENQUERY OPENROWSET OPENXML OPERATION OPTION OR ORDER OUTER
    OUTPUT OVER OVERLAPS OVERRIDE OWNER PACKAGE PAGE PAGES PARAMETER
    PARTIAL PARTITION PARTITIONS PASSWORD PATH PERCENT PERCENTILE_CONT
    PERCENTILE_DISC PERM PERMANENT PIVOT PLAN PLSQL PRECISION
    PREDICT PREPARE PRESERVE PRIMARY PRINT PRIOR PRIVILEGES PROC
    PROCEDURE PROCESSAUTHID PUBLIC PURGE QUERY QUOTES RAISERROR RANGE
    READ READS READTEXT REAL REBUILD RECONFIGURE RECOVER RECURSIVE
    REF REFERENCES REFERENCING REGEXP REINDEX REJECT RELATIVE RELEASE
    RELOCATE RENAME REPEATABLE REPLICATION REQUIRE RES RESET RESIGNAL
    RESOURCE RESTART RESTORE RESTRICT RESULT RETURN RETURNS REVERSE
    REVOKE RIGHT ROLE ROLLBACK ROLLUP ROUTINE ROW ROWCOUNT ROWGUIDCOL
    ROWS RULE SAVE SAVEPOINT SCHEMA SCHEMAS SCOPE SCROLL SEARCH
    SECOND SECTION SECURITY SEGMENT SELECT SEQUENCE SESSION SESSION_USER
    SET SETUSER SHOW SHUTDOWN SIBLINGS SIGNAL SIMILAR SIZE SMALLINT
    SNAPSHOT SOME SORT SPACE SPECIFIC SPECIFICTYPE SQL SQLCODE SQLERROR
    SQLEXCEPTION SQLSTATE SQLWARNING STABLE STANDARD START STARTPOINT
    STATEMENT STATIC STATISTICS STATUS STAY STORAGE STRAIGHT_JOIN
    STRING STRUCTURE STYLE SUBCLASS_ORIGIN SUBJECT SUBTYPE SUPERUSER
    SUSPEND SWITCH SYMMETRIC SYNONYM SYSBACKUP SYSDBA SYSDG SYSOPR
    SYSOUT SYSTEM_USER TABLE TABLES TABLESAMPLE TABLESPACE TEMP TEMPLATE
    TEMPORARY TERMINATE TEXT TEXTSIZE THEN TIME TIMESTAMP TIMESTAMPADD
    TIMESTAMPDIFF TINYINT TO TOP TRAILING TRAN TRANSACTION TRANSFORM
    TRIGGER TRIGGERS TRUE TRUNCATE TRY TSEQUAL TYPE UNBOUNDED
    UNCOMMITTED UNDER UNDO UNION UNIQUE UNKNOWN UNLIMITED UNLOCK UNPIVOT
    UNTIL UNUSABLE UPDATE UPDATETEXT UPPER USAGE USE USER USING
    VALUE VALUES VARBINARY VARCHAR VARIABLE VARYING VERBOSE VERSION
    VIEW VIRTUAL VISIBLE WAIT WHEN WHENEVER WHERE WHILE WINDOW WITH
    WITHIN WITHOUT WORK WRITE YEAR ZONE
  `,
  builtin: `
    AVG COUNT MAX MIN SUM
    ABS CEIL CEILING COALESCE CONCAT CONVERT COS COSH CURDATE CURTIME
    DATABASE DATADIFF DATENAME DATEPART DAY DB_NAME DEFAULT DELETE
    DIFFERENCE DISTINCT DM_SQL_CREATE_HUGE_TABLE DUAL
    EXISTS EXP FLOOR GETDATE GETUTCDATE GREATEST GROUPING
    HASH_BYTES IDENT_CURRENT IDENT_INCR IDENT_SEED IDENTITY INDEX
    ISDATE ISNULL ISNUMERIC LAG LEAD LEFT LEN LOG LOG10 LOWER LTRIM
    MONTH NCHAR NEWID NEWSEQUENTIALID NVL OPENQUERY OPENROWSET
    PARSE PATINDEX POWER QUOTENAME RAND REPLACE REPLICATE REVERSE
    RIGHT ROUND ROW_NUMBER RTRIM SESSION_USER SIGN SIN SINH SPACE
    SQRT SQUARE STUFF SUBSTRING SUM SUSER_SNAME SYSDATETIME
    SESSIONPREFIX SOUNDEX SPACE SQRT SQUARE STUFF SUBSTRING
    SYSTEM_USER TAN TANH TEXTVALID TO_CHAR TO_DATE TO_NUMBER
    TRANSACTION TRIM TYPE UPDATE UPPER USER USER_NAME VAR VARIANCE
    V$BUFFER_POOL_STATISTICS V$DATAFILE V$DEADLOCK_HISTORY V$INSTANCE
    V$LOCK V$MEMORY_INFO V$PARAMETER V$SESSION V$SESSIONS
    V$SQLAREA V$SQL_HISTORY V$SYSSTAT V$VERSION
    DBA_DATA_FILES DBA_SEGMENTS DBA_TABLES DBA_TABLESPACES
    ALL_TABLES ALL_TAB_COLUMNS USER_TABLES
    DM_INI DBMS_XPLAN PLAN_TABLE
  `,
  types: `
    BIGINT BINARY BIT BLOB BOOLEAN CHAR CLOB DATE DATETIME
    DEC DECIMAL DOUBLE FLOAT IDENTITY INT INTEGER INTERVAL
    MEDIUMINT NATIONAL NCHAR NUMBER NUMERIC NVARCHAR RAW
    REAL ROWID SERIAL SMALLINT TEXT TIME TIMESTAMP TINYINT
    VARCHAR VARCHAR2 VARRAY VARYING XML
  `,
  plsqlQuotingMechanism: true,
  doubleQuotedStrings: false,
  spaceAfterDashes: false,
  identifierQuotes: '"',
  caseInsensitiveIdentifiers: true,
});

/* ───── Oracle PL/SQL dialect ───── */
const OracleDialect = SQLDialect.define({
  keywords: `
    ABORT ABS ACCESS ADD AFTER ALL ALTER ANALYZE AND ANY ARCHIVE ARCHIVELOG AS
    ASC ASSOCIATE AT AUDIT AUTHORIZATION AUTOEXTEND BACKUP BECOME BEFORE BEGIN
    BETWEEN BLOCK BODY BULK BY CACHE CALL CANCEL CASCADE CASE CHANGE CHECK
    CHECKPOINT CLOSE CLUSTER COALESCE COLUMN COLUMNS COMMENT COMMIT COMMITTED
    COMPILE COMPOUND COMPUTE CONNECT CONNECTION CONSTRAINT CONSTRAINTS CONTAINS
    CONTENT CONTINUE CONTROLFILE CONVERT CORRUPTION COST COUNT CREATE CROSS
    CUBE CURRENT CURSOR CYCLE DATA DATABASE DATAFILE DATAFILES DAY DBA DEALLOCATE
    DEBUG DECLARE DEFAULT DEFERRABLE DEFERRED DELETE DENSE_RANK DESC DIRECTORY
    DISABLE DISCONNECT DISK DISMOUNT DISTINCT DISTRIBUTED DROP DUMP EACH ELSE
    ENABLE ENCRYPT END ESCAPE EVENT EXCEPT EXCEPTION EXCEPTIONS EXCLUDE EXECUTE
    EXISTS EXIT EXPLAIN EXTENT EXTERNALLY FAILED FETCH FILE FLASHBACK FOR FORALL
    FORCE FOREIGN FREELIST FREELISTS FREEPOOL FROM FULL FUNCTION GLOBAL GO GOTO
    GRANT GROUP GROUPING HASH HAVING HEAP HOUR IDENTIFIED IDENTITY IF IMMEDIATE
    IN INACTIVE INCLUDING INCREMENT INDEX INDEXES INDICATOR INITIAL INITIALLY
    INITRANS INSERT INSTANCE INSTEAD INT INTERSECT INTO INVALIDATE IS ISOLATION
    JAVA JOIN KEY KILL LANGUAGE LATERAL LEVEL LIBRARY LIKE LIMIT LINK LIST
    LOB LOCAL LOCK LOG LOGFILE LOGGING LOGICAL LOGON LOOP MAIN MANAGE MANAGED
    MASTER MATCHED MATERIALIZED MAXEXTENTS MAXSIZE MAXVALUE MEMBER MERGE MINEXTENTS
    MINIMIZE MINUS MINUTE MINVALUE MLSLABEL MODE MODEL MODIFY MONITOR MONTH
    MOUNT MOVE MOVEMENT MULTISET NATIONAL NATURAL NESTED NEW NEXT NO NOARCHIVELOG
    NOAUDIT NOCACHE NOCOMPRESS NOCYCLE NOFORCE NOLOGGING NOMAXVALUE NOMINVALUE
    NONE NOORDER NORELY NORESETLOGS NORMAL NOSORT NOT NOTFOUND NOWAIT NULL
    NULLS NUMBER NUMERIC OBJECT OF OFFLINE OFFSET OID OLTP ON ONLINE ONLY OPEN
    OPERATOR OPTIMAL OPTION OR ORDER ORACLE ORGANIZATION OTHERS OUT OUTLINE
    OVER OVERFLOW OVERLAPS OWN PACKAGE PARALLEL PARTITION PARTITIONS PASSWIDTH
    PASSWORD PCTFREE PCTINCREASE PCTTHRESHOLD PCTUSED PCTVERSION PERCENT PERCENTILE
    PERMANENT PFILE PIPELINED PIVOT PLAN PLS_INTEGER PRECISION PRESERVE PRIMARY
    PRIVATE PRIVILEGES PROCEDURE PROFILE PUBLIC PURGE QUERY QUOTA RANGE READ
    READS REBUILD RECOVER RECOVERY RECYCLE REDO REDUCED REF REFERENCES REFERENCING
    REGEXP REJECT RELY RENAME REPLACE RESET RESETLOGS RESOURCE RESTRICT RESTRICTED
    RESULT RESUMABLE RETURN RETURNING REUSE REVOKE RIGHT ROLE ROLLBACK ROLLUP
    ROW ROWID ROWNUM ROWS RULE SAMPLE SAVE SAVEPOINT SCAN SCHEMA SCHEMAS SCOPE
    SCN SEARCH SECOND SECTION SECURE SEGMENT SELECT SEQUENCE SEQUENTIAL SERIALIZABLE
    SESSION SET SHARED SHARD SHOW SHUTDOWN SIBLINGS SID SIGNAL SIZE SKIP SMALLFILE
    SNAPSHOT SOME SORT SPECIFICATION SPLIT SQL SQLCODE SQLDATA SQLERROR SQLEXCEPTION
    SQLSTATE SQLWARNING STANDBY START STATEMENT STATIC STATISTICS STORAGE STORE
    SUBTYPE SUCCESSFUL SWITCH SYNONYM SYSDATE SYSTEM TABLE TABLES TABLESPACE
    TABLESPACES TEMPFILE TEMPLATE TEMPORARY TEST THAN THE THEN THROUGH TIES TIME
    TIMESTAMP TO TRACE TRACKING TRANSACTION TRIGGER TRUNCATE TRUST TYPE UB2 UB4
    UGA UID UNARCHIVED UNBOUNDED UNDER UNDO UNION UNIQUE UNLIMITED UNLOCK UNPIVOT
    UNTIL UNUSABLE UPDATE UPPER UPSERT USAGE USE USER USING VALIDATE VALIDATION
    VALUE VALUES VARRAY VARYING VERSION VIEW WAIT WHEN WHENEVER WHERE WHILE WITH
    WITHIN WITHOUT WORK WRITE WRITES XID YEAR ZONE
  `,
  builtin: `
    ABS ADD_MONTHS ASCII ASIN ATAN AVG BFILENAME BIN_TO_NUM BITAND
    CAST CEIL CHARTOROWID CHR COALESCE COMPOSE CONCAT CONVERT CORR
    COSH COUNT COVAR_POP COVAR_SAMP CUME_DIST CURRENT_DATE CURRENT_TIMESTAMP
    CV DATE DAYS_BETWEEN DBTIMEZONE DECODE DECOMPOSE DENSE_RANK
    DEREF DUAL DUMP EMPTY_BLOB EMPTY_CLOB EXISTS EXP EXTRACT
    FIRST FIRST_VALUE FLOOR FOLLOWING GREATER GREATEST GROUPING GROUPING_ID
    HEXTORAW INITCAP INSTR INSTRB LAST LAST_DAY LAST_VALUE LATERAL
    LEAST LENGTH LENGTHB LN LOCALTIMESTAMP LOWER LPAD LTRIM
    MAKE_REF MAX MEDIAN MIN MOD MONTHS_BETWEEN NANVL NEW_TIME NEXT_DAY
    NLS_CHARSET_DECL_LEN NLS_CHARSET_ID NLS_CHARSET_NAME NLS_INITCAP NLS_LOWER
    NLS_SORT NLS_UPPER NLSSORT NULLIF NUMTODSINTERVAL NUMTOYMINTERVAL
    NVL NVL2 ORA_DST_AFFECT ORA_DST_CONVERT ORA_DST_ERROR ORA_HASH
    PATH PERCENT_RANK PERCENTILE_CONT PERCENTILE_DISC POWER PREDICTION
    PREDICTION_BOUNDS PREDICTION_COST PREDICTION_DETAILS PREDICTION_PROBABILITY
    PREDICTION_SET PRESENTNNV PRESENTV PREVIOUS PTF RANK RATIO_TO_REPORT
    RAWTOHEX RAWNUM RAWTOCHAR RAWTONHEX REMAINDER REPLACE
    ROUND ROW_NUMBER RPAD RTRIM SESSIONTIMEZONE SHA1 SHA2 SIGN SIN
    SINH SOUNDEX SQRT STDDEV STDDEV_POP STDDEV_SAMP SUBSTR SUBSTRB
    SUM SYSDATE SYSTIMESTAMP TABLE TAN TANH TIME TIMESTAMP
    TO_BINARY_DOUBLE TO_BINARY_FLOAT TO_CHAR TO_CLOB TO_DATE TO_DSINTERVAL
    TO_LOB TO_MULTI_BYTE TO_NCHAR TO_NCLOB TO_NUMBER TO_RAW TO_SINGLE_BYTE
    TO_TIMESTAMP TO_TIMESTAMP_TZ TO_YMINTERVAL TRANSLATE TRIM TRUNC TZ_OFFSET
    UI UID UNISTR UPDATEXML UPPER USER USERENV UUID VALUE VAR_POP
    VAR_SAMP VARIANCE VARYING VSIZE WIDTH_BUCKET XMLAGG XMLCAST XMLCOLATTVAL
    XMLCOMMENT XMLCONCAT XMLDIFF XMLELEMENT XMLEXISTS XMLFOREST XMLISVALID
    XMLNAMESPACES XMLPARSE XMLPI XMLQUERY XMLROOT XMLSEQUENCE XMLSERIALIZE
    XMLTABLE XMLTRANSFORM XMLWRITE YEAR
    V$ARCHIVE_DEST V$ARCHIVED_LOG V$ASM_DISK V$ASM_DISKGROUP V$BACKUP
    V$DATABASE V$DATAFILE V$DBLINK V$DIAG_INFO V$EVENT_NAME V$INSTANCE
    V$LOCK V$LOG V$LOGFILE V$LOG_HISTORY V$MYSTAT V$NLS_PARAMETERS
    V$PARAMETER V$PGASTAT V$PROCESS V$RECOVERY_FILE_DEST V$RECOVERY_LOG
    V$RESERVED_WORDS V$SESSION V$SESSION_LONGOPS V$SESSION_WAIT
    V$SGA V$SGASTAT V$SEGMENT_STATISTICS V$SQL V$SQL_PLAN V$SQLAREA
    V$SYSSTAT V$SYSTEM_EVENT V$TABLESPACE V$TEMPFILE V$THREAD
    V$TRANSACTION V$UNDOSTAT V$VERSION V$WAITSTAT
    ALL_ALL_TABLES ALL_CONS_COLUMNS ALL_CONSTRAINTS ALL_DB_LINKS ALL_DEF_AUDIT_OPTS
    ALL_INDEXES ALL_IND_COLUMNS ALL_OBJECTS ALL_SEQUENCES ALL_SOURCE ALL_SYNONYMS
    ALL_TAB_COLUMNS ALL_TAB_COMMENTS ALL_TAB_PRIVS ALL_TABLES ALL_TRIGGERS ALL_USERS
    ALL_VIEWS
    DBA_AUDIT_EXISTS DBA_AUDIT_OBJECT DBA_AUDIT_SESSION DBA_AUDIT_STATEMENT
    DBA_AUDIT_TRAIL DBA_DATA_FILES DBA_DDL_LOCKS DBA_DML_LOCKS
    DBA_ERRORS DBA_EXP_FILES DBA_EXP_OBJECTS DBA_EXTENTS DBA_FREE_SPACE
    DBA_HIST_ACTIVE_SESS_HISTORY DBA_HIST_SNAPSHOT DBA_HIST_SQLTEXT
    DBA_INDEXES DBA_IND_COLUMNS DBA_JOBS DBA_OBJECTS DBA_OBJ_AUDIT_OPTS
    DBA_PRIV_AUDIT_OPTS DBA_PROFILES DBA_ROLES DBA_ROLE_PRIVS DBA_SEGMENTS
    DBA_SEQUENCES DBA_SOURCE DBA_SYNONYMS DBA_SYS_AUDIT_OPTS DBA_SYS_PRIVS
    DBA_TAB_COLUMNS DBA_TAB_COMMENTS DBA_TAB_PRIVS DBA_TABLES DBA_TABLESPACES
    DBA_TRIGGERS DBA_TS_QUOTAS DBA_USERS DBA_VIEWS
    USER_ARGUMENTS USER_AUDIT_OBJECT USER_AUDIT_SESSION USER_AUDIT_STATEMENT
    USER_AUDIT_TRAIL USER_CATALOG USER_CLUSTERS USER_COL_COMMENTS USER_COL_PRIVS
    USER_CONSTRAINTS USER_CONS_COLUMNS USER_DB_LINKS USER_DEPENDENCIES
    USER_ERRORS USER_EXTENTS USER_FREE_SPACE USER_INDEXES USER_IND_COLUMNS
    USER_JOBS USER_OBJECTS USER_OBJ_AUDIT_OPTS USER_PASSWORD_LIMITS
    USER_PROCEDURES USER_ROLE_PRIVS USER_SEGMENTS USER_SEQUENCES USER_SNAPSHOTS
    USER_SOURCE USER_SYNONYMS USER_SYS_PRIVS USER_TAB_COLUMNS USER_TAB_COMMENTS
    USER_TAB_PRIVS USER_TABLES USER_TABLESPACES USER_TRIGGERS USER_TS_QUOTAS
    USER_TYPES USER_USERS USER_VIEWS
    DBMS_OUTPUT DBMS_SQL DBMS_XPLAN DBMS_WORKLOAD_REPOSITORY
    UTL_FILE UTL_HTTP UTL_SMTP UTL_TCP
    PLAN_TABLE DUAL
  `,
  types: `
    BFILE BINARY_BIGINT BINARY_DOUBLE BINARY_FLOAT BINARY_INTEGER
    BLOB BOOLEAN CHAR CHARACTER CLOB DATE DEC DECIMAL DOUBLE
    FIXED FLOAT INT INTEGER INTERVAL LARGE LONG MATERIALIZED
    MONTH NCHAR NCLOB NUMBER NUMERIC NVARCHAR2 NVARCHAR
    PLS_INTEGER PRECISION RAW REAL ROWID SECOND SIGNSMALLINT
    SMALLINT STRING TIMESTAMP TIME UROWID VARCHAR VARCHAR2 YEAR
    SYS_REFCURSOR XMLTYPE
  `,
  plsqlQuotingMechanism: true,
  doubleQuotedStrings: false,
  spaceAfterDashes: false,
  identifierQuotes: '"',
  caseInsensitiveIdentifiers: true,
});

/** Resolve SQLDialect from a db_type string */
function dialectForDbType(dbType: string): { dialect: SQLDialect; uc: boolean } {
  switch (dbType) {
    case "oracle":
      return { dialect: OracleDialect, uc: true };
    case "dameng":
      return { dialect: DamengDialect, uc: true };
    case "postgresql":
      return { dialect: PostgreSQL, uc: false };
    case "mysql":
    default:
      return { dialect: MySQL, uc: false };
  }
}

@customElement("script-editor")
export class ScriptEditor extends LitElement {
  /** Initial / current SQL content */
  @property({ type: String }) content = "";

  /** Target DB dialect: 'mysql' | 'postgresql' | 'oracle' | 'dameng' */
  @property({ type: String }) dbType = "mysql";

  /** When true, the editor is read-only */
  @property({ type: Boolean }) readonly = false;

  /** CodeMirror EditorView instance (created in firstUpdated) */
  editorView: EditorView | null = null;

  static styles = css`
    :host { display: block; }
    .editor-wrapper { border: 1px solid var(--border); border-radius: var(--radius-sm); overflow: hidden; }
    .editor-wrapper .cm-editor { height: 200px; }
    .editor-wrapper .cm-scroller { overflow: auto; }
  `;

  override connectedCallback() {
    super.connectedCallback();
  }

  override firstUpdated() {
    this._mountEditor(this.content, this.dbType, this.readonly);
  }

  override disconnectedCallback() {
    this._destroyEditor();
    super.disconnectedCallback();
  }

  override updated(changedProperties: Map<string, unknown>) {
    if (changedProperties.has("dbType")) {
      // Destroy and recreate editor with new dialect
      const currentContent = this.editorView?.state.doc.toString() ?? this.content;
      this._destroyEditor();
      this._mountEditor(currentContent, this.dbType, this.readonly);
    }
    if (changedProperties.has("readonly") && this.editorView) {
      // Re-mount if readonly changes
      const currentContent = this.editorView.state.doc.toString();
      this._destroyEditor();
      this._mountEditor(currentContent, this.dbType, this.readonly);
    }
  }

  private _mountEditor(doc: string, dbType: string, readOnly: boolean) {
    const container = this.renderRoot.querySelector(".editor-wrapper") as HTMLElement;
    if (!container) return;

    const { dialect, uc } = dialectForDbType(dbType);

    this.editorView = new EditorView({
      state: EditorState.create({
        doc,
        extensions: [
          basicSetup,
          sql({ dialect, upperCaseKeywords: uc }),
          oneDark,
          EditorView.editable.of(!readOnly),
          EditorView.updateListener.of((update) => {
            if (update.docChanged) {
              this.content = update.state.doc.toString();
              this.dispatchEvent(
                new CustomEvent("content-change", {
                  detail: { content: this.content },
                  bubbles: true,
                  composed: true,
                })
              );
            }
          }),
        ],
      }),
      parent: container,
    });
  }

  private _destroyEditor() {
    if (this.editorView) {
      this.editorView.destroy();
      this.editorView = null;
    }
  }

  /** Set the editor content programmatically (replaces entire doc) */
  setContent(newContent: string) {
    if (this.editorView) {
      const doc = this.editorView.state.doc;
      this.editorView.dispatch({
        changes: { from: 0, to: doc.length, insert: newContent },
      });
    } else {
      this.content = newContent;
    }
  }

  /** Get the current editor content */
  getContent(): string {
    return this.editorView?.state.doc.toString() ?? this.content;
  }

  override render() {
    return html`<div class="editor-wrapper"></div>`;
  }
}

declare global {
  interface HTMLElementTagNameMap {
    "script-editor": ScriptEditor;
  }
}
