CREATE TABLE IF NOT EXISTS worker_leases (
  lease_name VARCHAR(128) NOT NULL PRIMARY KEY,
  owner_id CHAR(36) NOT NULL,
  fencing_token BIGINT UNSIGNED NOT NULL DEFAULT 0,
  expires_at DATETIME NOT NULL,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
