CREATE TABLE IF NOT EXISTS audit_log_entries (
  id VARCHAR(64) NOT NULL COMMENT '审计条目 ID',
  event_type VARCHAR(64) NOT NULL COMMENT '审计事件类型',
  level ENUM('info', 'warning', 'error', 'critical') NOT NULL COMMENT '审计级别',
  user_id VARCHAR(64) NULL COMMENT '操作用户 ID',
  username VARCHAR(255) NULL COMMENT '操作用户名',
  user_role VARCHAR(32) NULL COMMENT '操作用户角色',
  action VARCHAR(128) NOT NULL COMMENT '操作名称',
  resource_type VARCHAR(64) NULL COMMENT '资源类型',
  resource_id VARCHAR(255) NULL COMMENT '资源 ID',
  details_json JSON NULL COMMENT '脱敏操作详情',
  approval_request_id VARCHAR(64) NULL COMMENT '审批请求 ID',
  client_ip VARCHAR(64) NULL COMMENT '客户端 IP',
  user_agent VARCHAR(512) NULL COMMENT '客户端 User-Agent',
  result ENUM('success', 'failure', 'pending') NOT NULL COMMENT '操作结果',
  error_message VARCHAR(1000) NULL COMMENT '规范化错误信息',
  timestamp_ms BIGINT UNSIGNED NOT NULL COMMENT '事件时间戳（毫秒）',
  created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) COMMENT '持久化时间',
  PRIMARY KEY (id),
  KEY idx_audit_log_event_time (event_type, timestamp_ms),
  KEY idx_audit_log_user_time (user_id, timestamp_ms),
  KEY idx_audit_log_resource_time (resource_type, resource_id, timestamp_ms),
  KEY idx_audit_log_result_time (result, timestamp_ms)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='通用持久审计日志表';
