ALTER TABLE agent_tool_idempotency
  MODIFY COLUMN id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '工具幂等记录 ID',
  MODIFY COLUMN actor_id INT UNSIGNED NOT NULL COMMENT '操作员用户 ID',
  MODIFY COLUMN session_id VARCHAR(512) NOT NULL COMMENT '会话标识',
  MODIFY COLUMN session_hash CHAR(64) NOT NULL COMMENT '会话标识 SHA-256',
  MODIFY COLUMN tool_name VARCHAR(128) NOT NULL COMMENT '工具名称',
  MODIFY COLUMN idempotency_key VARCHAR(128) NOT NULL COMMENT '跨请求幂等键',
  MODIFY COLUMN arguments_hash CHAR(64) NOT NULL COMMENT '工具参数 SHA-256',
  MODIFY COLUMN state ENUM('running','completed','failed') NOT NULL COMMENT '幂等执行状态',
  MODIFY COLUMN result_json JSON NULL COMMENT '已完成工具结果',
  MODIFY COLUMN created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  MODIFY COLUMN updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  COMMENT = 'Agent 工具跨请求幂等记录';
