import { mkdir, readFile, writeFile } from 'node:fs/promises';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import type { TSchema } from '@sinclair/typebox';
import { PublicApiSchemas } from './public-api.js';

const root = resolve(dirname(fileURLToPath(import.meta.url)), '../../../..');
const openApiPath = resolve(root, 'docs/slide/openapi.json');
const clientPath = resolve(root, 'frontend/src/api/generated/public-api.ts');

function stable(value: unknown): unknown {
  if (Array.isArray(value)) return value.map(stable);
  if (value && typeof value === 'object') {
    return Object.fromEntries(Object.entries(value as Record<string, unknown>)
      .sort(([a], [b]) => a.localeCompare(b))
      .map(([key, child]) => [key, stable(child)]));
  }
  return value;
}

function refSchema(schema: TSchema): Record<string, string> {
  return { $ref: `#/components/schemas/${schema.$id}` };
}

export function buildOpenApiDocument() {
  return stable({
    openapi: '3.1.0',
    info: { title: 'Slide Public API', version: '0.9.0' },
    paths: {
      '/api/health': { get: { operationId: 'getHealth', responses: { '200': { description: 'Service health', content: { 'application/json': { schema: refSchema(PublicApiSchemas.HealthResponse) } } } } } },
      '/api/adapters/capabilities': { get: { operationId: 'getAdapterCapabilities', security: [{ bearerAuth: [] }], responses: { '200': { description: 'Database adapter capabilities', content: { 'application/json': { schema: refSchema(PublicApiSchemas.AdapterCapabilitiesResponse) } } } } } },
      '/api/database/instances': { get: { operationId: 'listDatabaseInstances', security: [{ bearerAuth: [] }], responses: { '200': { description: 'Redacted managed database instances', content: { 'application/json': { schema: refSchema(PublicApiSchemas.DatabaseInstancesResponse) } } } } } },
    },
    components: {
      securitySchemes: { bearerAuth: { type: 'http', scheme: 'bearer', bearerFormat: 'JWT' } },
      schemas: PublicApiSchemas,
    },
  });
}

export function buildClientTypes(): string {
  return `// Generated by pnpm contracts:generate. Do not edit.\n\nexport type DatabaseType = 'mysql' | 'postgresql' | 'oracle' | 'dameng' | 'mongodb' | 'redis' | 'elasticsearch';\nexport type CapabilityState = 'declared' | 'configured' | 'verified' | 'degraded' | 'unsupported';\nexport type AdapterCapabilityName = 'connect' | 'query' | 'explain' | 'metrics' | 'health' | 'alerts' | 'reports' | 'writeApproval';\n\nexport interface HealthResponse {\n  status: 'ok';\n  timestamp: string;\n}\n\nexport interface AdapterCapability {\n  dbType: DatabaseType;\n  driver: string | null;\n  state: CapabilityState;\n  creatable: boolean;\n  capabilities: Partial<Record<AdapterCapabilityName, CapabilityState>>;\n  reason?: string;\n}\n\nexport interface AdapterCapabilitiesResponse {\n  adapters: AdapterCapability[];\n}\n\nexport interface DatabaseInstance {\n  id: number;\n  name: string;\n  db_type: DatabaseType;\n  db_version?: string | null;\n  data_size_gb?: number | null;\n  host: string;\n  port: number;\n  database_name: string;\n  username?: string | null;\n  health_status: 'healthy' | 'warning' | 'critical' | 'unknown';\n  health_score: number;\n  status: string;\n  created_at: string;\n  environment?: string | null;\n  description?: string | null;\n  hasCredential: boolean;\n  credentialVersion: number;\n  [key: string]: unknown;\n}\n\nexport type DatabaseInstancesResponse = DatabaseInstance[];\n`;
}

export async function generatePublicApi(): Promise<void> {
  await Promise.all([mkdir(dirname(openApiPath), { recursive: true }), mkdir(dirname(clientPath), { recursive: true })]);
  await Promise.all([
    writeFile(openApiPath, `${JSON.stringify(buildOpenApiDocument(), null, 2)}\n`),
    writeFile(clientPath, buildClientTypes()),
  ]);
}

export async function checkPublicApi(): Promise<boolean> {
  const expectedOpenApi = `${JSON.stringify(buildOpenApiDocument(), null, 2)}\n`;
  const expectedClient = buildClientTypes();
  const [actualOpenApi, actualClient] = await Promise.all([readFile(openApiPath, 'utf8'), readFile(clientPath, 'utf8')]);
  return actualOpenApi === expectedOpenApi && actualClient === expectedClient;
}

if (process.argv[1] && resolve(process.argv[1]) === fileURLToPath(import.meta.url)) {
  const check = process.argv.includes('--check');
  if (check) {
    const current = await checkPublicApi().catch(() => false);
    if (!current) {
      console.error('Generated API contracts are stale. Run pnpm contracts:generate.');
      process.exitCode = 1;
    }
  } else {
    await generatePublicApi();
  }
}
